[Task][69503] Build Favourite Screen
awesome-academy/Football_Stats_App pull request #10
Opened 2023-10-13 06:44 UTC by hlinh88

## [Task][69503] Build Favourite Screen

### [Redmine link]
https://edu-redmine.sun-asterisk.vn/issues/69503

#### Screenshots (nếu có)

https://github.com/awesome-academy/Football_Stats_App/assets/73870812/91a493b8-48c0-4b45-ab3e-d7ad3c04cef1

2023-10-13 06:53 UTC, dongtg-1485 requested changes

2023-10-13 06:53 UTC, dongtg-1485 commented on FootballStats/FootballStats/Data/Model/Favourite/FavouritePlayer.swift
> +struct FavouritePlayer {
```suggestion
struct FavouritePlayer: Codable {
```

Các object default thêm Codable và coding key đi em

2023-10-13 06:53 UTC, dongtg-1485 commented on FootballStats/FootballStats/Data/Source/Local/CoreDataService.swift
> +    func saveFavourite(thisStat: Stats) {
```suggestion
    func saveFavourite(thisStat: Stats) -> Observable<Void> {
```

2023-10-13 06:53 UTC, dongtg-1485 commented on FootballStats/FootballStats/Data/Source/Local/CoreDataService.swift
> +    func deleteFavourite(id: Int) {
```suggestion
    func deleteFavourite(id: Int) -> Observable<Void>  {
```

2023-10-13 06:53 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Detail/DetailViewModel.swift
> +            .disposed(by: disposeBag)
check lại logic đoạn này

2023-10-13 06:53 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Detail/DetailViewModel.swift
>              .disposed(by: disposeBag)
check tiếp logic đoạn này

2023-10-13 06:53 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Favourite/FavouriteViewController.swift
> +                }
```suggestion
                let cell = tableView.dequeueReusableCell(for: indexPath, cellType: FavouriteTableViewCell.self).then {
                    $0.configCell(thisFavourite: favourite)
                    $0.delegate = self
                }
```

2023-10-13 06:53 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Favourite/FavouriteViewModel.swift
> +            .disposed(by: disposeBag)
sửa lại tất cả các đoạn tương tự như này nhé

2023-10-13 14:44 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Detail/DetailViewModel.swift
> +        let voidDriver = [saveFavourite, deleteFavourite]
vẫn chưa ổn, làm lại nhé

2023-10-13 14:44 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Favourite/FavouriteViewModel.swift
> +            .disposed(by: disposeBag)
not good, tìm cách khác clean hơn

2023-10-15 16:09 UTC, tuta-3205 commented on FootballStats/FootballStats/Data/Model/Favourite/FavouritePlayer.swift
> +        case clubLogo
:v chắc k ba playerName hay player_name ấy

2023-10-15 16:09 UTC, tuta-3205 commented on FootballStats/FootballStats/Domain/Architecture/CoreDataErrorType.swift
> +    case checkFavouriteExistFailed
mình nghĩ chỗ này nên là getFailed, saveFailed, checkFailed

2023-10-15 16:09 UTC, tuta-3205 commented on FootballStats/FootballStats/Scenes/Detail/DetailViewController.swift
> +        }
Chỗ này xem lại nha, có thể code tối ưu hơn :v code đề xuất nhiều r, lần này tự check thử xem

2023-10-16 02:31 UTC, hlinh88 commented on FootballStats/FootballStats/Scenes/Detail/DetailViewModel.swift
> +        let voidDriver = [saveFavourite, deleteFavourite]
em đã tách ra thành 2 output thay vì gộp void driver ạ

2023-10-16 02:32 UTC, hlinh88 commented on FootballStats/FootballStats/Data/Model/Favourite/FavouritePlayer.swift
> +        case clubLogo
@tuta-3205 Model này t lấy theo Core Data Entity nên t đặt tên như này trong Core Data sẵn chứ không lấy từ API :v

2023-10-16 02:35 UTC, dongtg-1485 approved these changes

2023-10-16 03:15 UTC, daolq-2712 approved these changes
OK!

2023-10-16 03:16 UTC, merged