[Task][69500] Build Standing Screen
awesome-academy/Football_Stats_App pull request #8
Opened 2023-10-04 16:35 UTC by hlinh88

## [Task][69500] Build Standing Screen

### [Redmine link]
https://edu-redmine.sun-asterisk.vn/issues/69500

#### Screenshots (nếu có)
<img src="https://github.com/awesome-academy/Football_Stats_App/assets/73870812/ce856cc9-c9df-4b18-9ae6-994c28686af9" width="250">
<img src="https://github.com/awesome-academy/Football_Stats_App/assets/73870812/bd83f268-1083-475d-8229-d31287a2f279" width="250">

2023-10-05 01:51 UTC, ghost commented on FootballStats/FootballStats/Data/Model/Team/All.swift
> +struct All: Codable {
nên đặt tên clear xíu e

2023-10-05 01:51 UTC, ghost commented on FootballStats/FootballStats/Repository/ScheduleRepository.swift
> +        return(todayString)
```suggestion
        let todaysDate = Date()
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd"
        let todayString = dateFormatter.string(from: todaysDate)
        return todayString
```

2023-10-05 01:51 UTC, ghost commented on FootballStats/FootballStats/Repository/ScheduleRepository.swift
> +        return(lastWeekString)
```suggestion
        let lastWeekDate = NSCalendar.current.date(byAdding: .weekOfYear, value: -1, to: NSDate() as Date)
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd"
        let lastWeekString = dateFormatter.string(from: lastWeekDate!)
        return lastWeekString
```

2023-10-05 01:51 UTC, phonglh-2668 commented on FootballStats/FootballStats/Scenes/News/NewsViewModel.swift
> +        newsRepository.requestNews(completion: { (news: [News]?, error: Error?) in
```suggestion
        newsRepository.requestNews(completion: { news, error in
```

2023-10-05 01:51 UTC, ghost commented on FootballStats/FootballStats/Scenes/News/NewsViewModel.swift
> +                print(errorMessage)
nếu có lỗi nên show ra alert hay gì đó đi e :v

2023-10-05 01:51 UTC, phonglh-2668 commented on FootballStats/FootballStats/Scenes/Schedule/Cell/ScheduleTableViewCell.swift
> +class ScheduleTableViewCell: UITableViewCell {
final

2023-10-05 01:51 UTC, phonglh-2668 commented on FootballStats/FootballStats/Scenes/Schedule/ScheduleViewController.swift
> +            }.disposed(by: disposeBag)
break line e

2023-10-05 01:51 UTC, phonglh-2668 commented on FootballStats/FootballStats/Scenes/Schedule/ScheduleViewModel.swift
> +                print(errorMessage)
nếu có lỗi cũng show alert hay gì đó e, k print như này

2023-10-05 01:51 UTC, phonglh-2668 commented on FootballStats/FootballStats/Scenes/Schedule/ScheduleViewModel.swift
> +                let matchWeekText = "Matchweek \(schedules.league.round.last!)"
k force unwrap

2023-10-05 01:51 UTC, phonglh-2668 commented on FootballStats/FootballStats/Scenes/Standing/Cell/StandingTableViewCell.swift
> +class StandingTableViewCell: UITableViewCell {
final

2023-10-05 01:51 UTC, ghost commented on FootballStats/FootballStats/Scenes/Standing/StandingViewController.swift
> +            }.disposed(by: disposeBag)
break line

2023-10-05 01:51 UTC, ghost commented on FootballStats/FootballStats/Scenes/Standing/StandingViewModel.swift
> +                print(errorMessage)
tương tự

2023-10-05 01:51 UTC, ghost commented on FootballStats/FootballStats/Scenes/News/NewsViewController.swift
> +            }.disposed(by: disposeBag)
break line

2023-10-05 01:51 UTC, ghost commented on FootballStats/FootballStats/Repository/StandingRepository.swift
> +                                  headers: Constants.footballHeaders) { (returnedResponse: TeamsResponse!, error: Error?) in
```suggestion
                                  headers: Constants.footballHeaders) { returnedResponse, error in
```

2023-10-05 02:07 UTC, dongtg-1485 commented on FootballStats/FootballStats/Repository/ScheduleRepository.swift
> +            }
trả về duy nhất 1 response thôi em, phía nhận sẽ xử lý chứ ko for loop luôn tại đây

2023-10-05 02:07 UTC, dongtg-1485 commented on FootballStats/FootballStats/Repository/ScheduleRepository.swift
> +    }
xử lý date không nằm trong Schedule repository

2023-10-05 02:07 UTC, dongtg-1485 commented on FootballStats/FootballStats/Repository/StandingRepository.swift
> +                }
tưởng tự, response trả ra bên ngoài

2023-10-05 02:07 UTC, dongtg-1485 commented on FootballStats/FootballStats/Resources/Localizable.strings
> +"gradientColor4" = "#6976F6";
quản lý màu bằng file Asset và swift Gen nhé em, sao lại khai báo color vào file string như này

2023-10-05 02:07 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Schedule/ScheduleViewModel.swift
> +                let matchWeekText = "Matchweek \(schedules.league.round.last!)"
tuyệt đối không force unwrap

2023-10-05 02:07 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Standing/StandingViewModel.swift
> +                }
xử lý để accept value 1 lần, làm như này sẽ trigger event nhiều lần ở phía subscriber

2023-10-05 02:07 UTC, dongtg-1485 commented on FootballStats/FootballStats/Utils/Constants.swift
> +                                     "league": "39"]
những cái này xử lý ở APIService và Repository, không lạm dụng static properties

2023-10-05 03:50 UTC, dongtg-1485 commented on FootballStats/FootballStats/Extension/StringExtension.swift
> +}
xử lý date phải tạo extension của `Date` chứ em sao lại tạo vào String

2023-10-06 01:30 UTC, tuta-3205 approved these changes

2023-10-06 02:15 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/News/NewsViewModel.swift
> +        self.useCase = NewsUseCase(newsRepository: NewsRepositoryImpl())
use case khởi tạo từ bên ngoài rồi pass vào qua constructor

2023-10-06 02:15 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/News/NewsViewModel.swift
> +                    .asDriver(onErrorJustReturn: [])
không show loading à em

2023-10-06 02:15 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Schedule/ScheduleViewController.swift
> +                cellType: ScheduleTableViewCell.self)) { _, schedule, cell in
coding convention

2023-10-06 02:15 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Schedule/ScheduleViewModel.swift
> +        self.useCase = ScheduleUseCase(scheduleRepository: ScheduleRepositoryImpl())
khởi tạo từ bên ngoài

2023-10-06 02:15 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Standing/StandingViewModel.swift
> +        self.useCase = StandingUseCase(standingRepository: StandingRepositoryImpl())
khởi tạo từ bên ngoài

2023-10-06 06:45 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/News/NewsViewModel.swift
> +    var useCase = NewsUseCase(newsRepository: NewsRepositoryImpl())
không khởi tạo trực tiếp trong VM

2023-10-06 06:45 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/News/NewsViewModel.swift
> +    var navigator: NewsNavigatorType!
không force unwrap

2023-10-06 10:22 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/News/NewsViewController.swift
> +        bindViewModel()
binding này được gọi ở thời điểm khởi tạo ViewController khi implement `BindableType` rồi

2023-10-09 02:18 UTC, daolq-2712 requested changes
Pls check my comments!

2023-10-09 02:18 UTC, daolq-2712 commented on FootballStats/FootballStats/Repository/ScheduleRepository.swift
> +            "X-RapidAPI-Host": Constants.APIFootballHost
@hlinh88 
```suggestion
        let footballHeaders: HTTPHeaders = [
            "X-RapidAPI-Key": Constants.APIKey,
            "X-RapidAPI-Host": Constants.APIFootballHost
```
Mình nên move những cái dùng chung nhiều lần này vào file

`FootballStats/FootballStats/Data/Source/API/APIService.swift
`

2023-10-09 02:18 UTC, daolq-2712 commented on FootballStats/FootballStats/Repository/ScheduleRepository.swift
> +        let parameter = footballParameters.merging(dateParameter, uniquingKeysWith: +)
```suggestion
        let footballParameters = ["season": Constants.season,
                                  "league": Constants.leagueId]

        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd"
        let currentDate = Date().getCurrentDate()
        let lastweekDate = Date().getLastWeekDate()

        let dateParameter = ["to": dateFormatter.string(from: currentDate),
                             "from": dateFormatter.string(from: lastweekDate)]

        let parameter = footballParameters.merging(dateParameter, uniquingKeysWith: +)
```
Tách ra khai báo thành class `ScheduleRequest` đặt trong folder
`FootballStats/FootballStats/Data/Source/API/request`

2023-10-09 02:18 UTC, daolq-2712 commented on FootballStats/FootballStats/Repository/ScheduleRepository.swift
> +        .map { (result: FixturesResponse) in
``` suggestion
        .map { (result: ScheduleResponse) in
```
Đổi tên thành `ScheduleResponse` và đặt trong folder
`FootballStats/FootballStats/Data/Source/API/response`

2023-10-09 02:18 UTC, daolq-2712 commented on FootballStats/FootballStats/Repository/StandingRepository.swift
> +            "X-RapidAPI-Host": Constants.APIFootballHost
Tương tự bên trên

2023-10-09 02:18 UTC, daolq-2712 commented on FootballStats/FootballStats/Repository/StandingRepository.swift
> +        .map { (result: TeamsResponse) in
.

2023-10-09 02:18 UTC, daolq-2712 commented on FootballStats/FootballStats/Repository/StandingRepository.swift
> +        let footballParameters = ["season": Constants.season,
.

2023-10-09 02:18 UTC, daolq-2712 commented on FootballStats/Podfile
> +	pod 'RxRelay', '~> 5.1'
@hlinh88 
sao lại down ver xuống vậy em?

2023-10-09 02:58 UTC, hlinh88 commented on FootballStats/Podfile
> +	pod 'RxRelay', '~> 5.1'
@daolq-2712 
dạ em down ver để dùng dc lib RxSwiftUtilities để implement được ActivityIndicator ạ. ver mới của RxSwift nó không support cái ActivityIndicator với ErrorTracker nữa anh ạ

2023-10-09 03:30 UTC, dongtg-1485 commented on FootballStats/FootballStats/Application/AppDelegate.swift
> +           let viewModel = AppViewModel(navigator: navigator, useCase: useCase)
thiếu disposeBag

2023-10-09 03:30 UTC, dongtg-1485 commented on FootballStats/FootballStats/Application/AppDelegate.swift
>          getAPIKeys()
chuyển vào useCase của app, sau khi fetch xong API key mới next sang screen tiếp theo

2023-10-09 03:30 UTC, dongtg-1485 commented on FootballStats/FootballStats/Data/Model/Schedule/Schedule.swift
> +        case fixture, teams, goals, league
enum case biết tách từng line, không viết chung 1 line

2023-10-09 03:30 UTC, dongtg-1485 commented on FootballStats/FootballStats/Data/Source/Service/APIService.swift
> +                            observable.onCompleted()
sau khi error observable tự động terminate nên không cần gọi `.onCompleted()`

2023-10-09 03:30 UTC, dongtg-1485 commented on FootballStats/FootballStats/Repository/StandingRepository.swift
> +            }
dùng `map` operator nhé

2023-10-09 03:30 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/App/AppNavigator.swift
> +        window.makeKeyAndVisible()
khởi tạo tabbar trong navigator, không khởi tạo trong view bằng func static như thế này

2023-10-09 03:30 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/App/AppViewModel.swift
> +            .drive()
đang bị leak memory tại đây

2023-10-09 03:30 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Schedule/Cell/ScheduleTableViewCell.swift
> +    static var identifier = String(describing: ScheduleTableViewCell.self)
dùng lib `Reusable` luôn cho gọn nhé

2023-10-09 04:22 UTC, dongtg-1485 requested changes

2023-10-09 04:22 UTC, dongtg-1485 commented on FootballStats/FootballStats/Data/Model/News/News.swift
> +             img
```suggestion
        case title
        case url
        case img
```

2023-10-09 04:22 UTC, dongtg-1485 commented on FootballStats/FootballStats/Repository/StandingRepository.swift
> +            }
đoạn này em dùng Map kết hợp Reduce là đc mà sao phải làm cồng kềnh như này nhỉ

2023-10-09 04:22 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/App/AppNavigator.swift
> +        let tabBarVC = nib.instantiate(withOwner: nil, options: nil).first as? TabBarController
Các sub-viewController cũng phải khởi tạo trong này luôn

2023-10-09 04:22 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/App/AppUseCase.swift
> +    func getAPIKeys() {
```suggestion
    func getAPIKeys() -> Observable<void> {
```

2023-10-09 04:22 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/App/AppViewModel.swift
> +            })
```suggestion
            .flatMapLatest {
                return self.useCase.getAPIKeys()
                    ...
            }
```

2023-10-09 04:22 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/App/AppViewModel.swift
> +            .drive()
```suggestion
            .drive(onNext: { _ in
                self.navigator.toTabBar()
            })
```

2023-10-09 04:22 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/App/AppNavigator.swift
> +        let tabBarVC = nib.instantiate(withOwner: nil, options: nil).first as? TabBarController
dùng Reusable

2023-10-09 07:15 UTC, hlinh88 commented on FootballStats/FootballStats/Repository/StandingRepository.swift
> +            }
Chỗ này em chưa biết cách áp dụng reduce nên em dùng short-hand map rút gọn cho dễ nhìn ạ

2023-10-09 07:30 UTC, TuanKieuDev commented on FootballStats/FootballStats/Data/Source/API/Request/NewsRequest.swift
> +class NewsRequest: BaseRequest {
final

2023-10-09 07:30 UTC, TuanKieuDev commented on FootballStats/FootballStats/Data/Source/API/Request/ScheduleRequest.swift
> +class ScheduleRequest: BaseRequest {
final

2023-10-09 07:30 UTC, TuanKieuDev commented on FootballStats/FootballStats/Data/Source/API/Request/StandingRequest.swift
> +class StandingRequest: BaseRequest {
final

2023-10-09 07:33 UTC, dongtg-1485 approved these changes

2023-10-09 07:33 UTC, dongtg-1485 commented on FootballStats/FootballStats/Repository/StandingRepository.swift
> +        .catchErrorJustReturn([])
lỗi coding convention, đang thụt lề sai

2023-10-09 07:43 UTC, daolq-2712 approved these changes
LGTM!

2023-10-09 07:43 UTC, merged