[Task][69497] Build Stats Screen
awesome-academy/Football_Stats_App pull request #9
Opened 2023-10-11 06:13 UTC by hlinh88

## [Task][69497] Build Stats Screen

### [Redmine link]
https://edu-redmine.sun-asterisk.vn/issues/69497

#### Screenshots (nếu có)
<img src="https://github.com/awesome-academy/Football_Stats_App/assets/73870812/40b0108f-efe7-4484-bbc9-4f4a742f2a0d" width="250">
<img src="https://github.com/awesome-academy/Football_Stats_App/assets/73870812/a107994c-3de0-4271-843b-85607fb609b7" width="250">

2023-10-11 06:16 UTC, TuanKieuDev commented on FootballStats/FootballStats/Scenes/Detail/DetailViewController.swift
> +    private let noOfCellsInRow = 2
nên define ra Constant

2023-10-11 06:17 UTC, TuanKieuDev commented on FootballStats/FootballStats/Scenes/Stats/Cell/StatsCollectionViewCell.swift
> +        topView.layer.maskedCorners = [.layerMinXMinYCorner, .layerMaxXMinYCorner]
dùng Then

2023-10-11 06:18 UTC, TuanKieuDev commented on FootballStats/FootballStats/Scenes/Stats/Cell/StatsCollectionViewCell.swift
> +        bottomView.clipsToBounds = true
dùng Then

2023-10-11 06:19 UTC, TuanKieuDev commented on FootballStats/FootballStats/Scenes/Stats/StatsViewController.swift
> +    private let noOfCellsInRow = 2
như trên

2023-10-11 06:33 UTC, dongtg-1485 requested changes

2023-10-11 06:33 UTC, dongtg-1485 commented on FootballStats/FootballStats/Data/Model/Stats/Statistic.swift
> +    var shots: Shot
```suggestion
    var goals: GoalStat
    var cards: CardStat
    var team: TeamStat
    var games: GameStat
    var passes: PassStat
    var shots: ShotStat
```

2023-10-11 06:33 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/App/AppNavigator.swift
> +//        viewController.bindViewModel(to: viewModel)
sao lại comment các hàm binding vậy em ?

2023-10-11 06:33 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Detail/Cell/DetailCollectionViewCell.swift
> +    func configCell(thisRecord: String, index: Int) {
dùng enum để xác định, không dùng theo index

2023-10-11 06:33 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Detail/DetailNavigator.swift
> +    let navigationController: UINavigationController
```suggestion
    unowned let navigationController: UINavigationController
```

2023-10-11 06:33 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Detail/DetailViewController.swift
> +            .disposed(by: disposeBag)
subscribe 1 lần rồi set value cho cả 2 label luôn

2023-10-11 06:33 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Detail/DetailViewModel.swift
> +                           String(self.thisStat.statistics[0].shots.total ?? 0)]
nếu `statistics` có 0 elements thì sao ?

2023-10-11 06:33 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Stats/Cell/StatsCollectionViewCell.swift
> +    func configCell(thisStat: Stats, index: Int) {
dùng enum, không dùng index

2023-10-11 06:33 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Stats/Cell/StatsTableViewCell.swift
> +        }
logic đoạn này gây lú vậy em @@ sao lại dùng map ở đây

2023-10-11 06:33 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Stats/StatsViewController.swift
> +            }.disposed(by: disposeBag)
coding convention

2023-10-11 06:33 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Stats/StatsViewModel.swift
> +        }
tại sao đoạn này lại dùng `map` vậy ?

2023-10-11 09:48 UTC, phonglh-2668 commented on FootballStats/FootballStats/Scenes/Detail/DetailViewController.swift
> +            .disposed(by: disposeBag)
những thằng này chung 1 model hay không mà chia nhiều vậy e

2023-10-11 09:48 UTC, phonglh-2668 commented on FootballStats/FootballStats/Scenes/Detail/DetailViewController.swift
> +    var clubImageBiding: Binder<String> {
private

2023-10-11 09:48 UTC, phonglh-2668 commented on FootballStats/FootballStats/Scenes/Detail/DetailViewController.swift
> +    var playerImageBiding: Binder<String> {
private

2023-10-11 09:48 UTC, phonglh-2668 commented on FootballStats/FootballStats/Scenes/Detail/DetailViewController.swift
> +
break line

2023-10-11 09:48 UTC, phonglh-2668 commented on FootballStats/FootballStats/Scenes/Detail/DetailViewModel.swift
> +        let indicator: Driver<Bool>
tạo 1 thằng stats thôi được rồi e, bên kia dùng binder để show data ra, làm cách này dài dòng lê thê quá

2023-10-11 09:48 UTC, phonglh-2668 commented on FootballStats/FootballStats/Scenes/Stats/StatsViewController.swift
> +    @IBOutlet weak var testLabel: UILabel!
testlabel là sao e :v

2023-10-11 09:48 UTC, phonglh-2668 commented on FootballStats/FootballStats/Scenes/Stats/StatsViewController.swift
> +    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
break line

2023-10-11 09:48 UTC, phonglh-2668 commented on FootballStats/FootballStats/Scenes/Stats/StatsViewModel.swift
> +        let yellowcards = self.useCase.getStats(category: "topyellowcards")
dùng enum define cho mấy category e

2023-10-11 09:48 UTC, phonglh-2668 commented on FootballStats/FootballStats/Scenes/Stats/StatsViewModel.swift
> +            .flatMapLatest { _ in
nếu là void thì bỏ `_ in` đi cũng được e

2023-10-11 09:48 UTC, phonglh-2668 commented on FootballStats/FootballStats/Scenes/Stats/StatsViewModel.swift
> +                self.navigator.toDetail(thisStat: stat)
sao k dùng ở drive mà dùng ở do vậy e ?

2023-10-11 11:10 UTC, hlinh88 commented on FootballStats/FootballStats/Scenes/App/AppNavigator.swift
> +//        viewController.bindViewModel(to: viewModel)
dạ em quên mất ko uncomment. Em comment để nó không gọi API vì API em nó limit ạ

2023-10-11 11:11 UTC, hlinh88 commented on FootballStats/FootballStats/Scenes/Detail/DetailViewController.swift
> +            .disposed(by: disposeBag)
@dongtg-1485 đoạn này em chưa clear lắm cách làm như nào ạ :v

2023-10-11 11:13 UTC, hlinh88 commented on FootballStats/FootballStats/Scenes/Detail/DetailViewModel.swift
> +                           String(self.thisStat.statistics[0].shots.total ?? 0)]
![Screenshot 2023-10-11 at 6 12 40 pm](https://github.com/awesome-academy/Football_Stats_App/assets/73870812/371c91ad-8c7e-4d7c-af8c-1dbdafafbadf)
cái API em dùng nó trả 1 cái array statistics là 1 array luôn có 1 element để bọc các cái kia nên nó không có hoặc chỉ có 1 element ạ

2023-10-11 11:14 UTC, hlinh88 commented on FootballStats/FootballStats/Scenes/Stats/StatsViewModel.swift
> +        }
@dongtg-1485 em có thử áp dụng các operator nhưng chưa được nên em dùng tạm `BehaviorRelay` lấy element 0 Stats của các `Observable` trong var `group` ạ

2023-10-11 11:15 UTC, hlinh88 commented on FootballStats/FootballStats/Scenes/Detail/DetailViewController.swift
> +            .disposed(by: disposeBag)
@phonglh-2668 dạ cái Detail screen này nó show nhiều loại stats nên hơi nhiều loại như này ạ :v

2023-10-11 11:16 UTC, hlinh88 commented on FootballStats/FootballStats/Scenes/Detail/DetailViewModel.swift
> +        let indicator: Driver<Bool>
@phonglh-2668 dạ em cũng có thể để 1 thằng Stat nhưng xử lý logic lấy value nó sẽ hơi rối trong `ViewController` nên em tách ra luôn như này để xử lý lấy data trong `ViewModel` ạ

2023-10-11 11:17 UTC, hlinh88 commented on FootballStats/FootballStats/Scenes/Stats/StatsViewModel.swift
> +                self.navigator.toDetail(thisStat: stat)
@phonglh-2668 em có tham khảo các proj của các anh thì em thấy các anh dùng `do` để xử lý navigator ạ :v

2023-10-11 11:57 UTC, dongtg-1485 requested changes

2023-10-11 11:57 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Detail/Cell/DetailCollectionViewCell.swift
> +}
Tách file
Không bao giờ để chung file nhiều class, struct, enum...

2023-10-11 11:57 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Detail/Cell/DetailCollectionViewCell.swift
> +    func getTitle() -> String {
```suggestion
    var title: String {
```

2023-10-11 11:57 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Detail/DetailViewController.swift
> +            .disposed(by: disposeBag)
```suggestion
        output.playerName
            .drive(onNext: { [weak self] playerName in
                guard let self = self else { return }
                self.playerNameTitleLabel.text = playerName
                self.playerNameLabel.text = playerName
            })
            .disposed(by: disposeBag)
```

2023-10-11 11:57 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Stats/Cell/StatsCollectionViewCell.swift
> +enum StatsType: Int {
tách file

2023-10-11 11:57 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Stats/Cell/StatsCollectionViewCell.swift
> +    func getTitle() -> String {
dùng computed properties thay cho function

2023-10-11 11:57 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Stats/Cell/StatsCollectionViewCell.swift
> +            return String(thisStat.statistics[0].cards.yellow)
Lỗi lặp lại của comment trước.
Nếu `statistics` có 0 element thì sao ?

2023-10-11 11:57 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Stats/Cell/StatsCollectionViewCell.swift
> +    func getColor() -> [Any] {
```suggestion
    var gradientColors: [CGColor] {
```

2023-10-11 11:57 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Stats/Cell/StatsTableViewCell.swift
> +        clubImageView.sd_setImage(with: URL(string: thisStat.statistics[0].team.logo), placeholderImage: nil)
lỗi lặp lại tiếp, nếu `statistics` có 0 element thì sao ?

2023-10-11 11:57 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Stats/Cell/StatsTableViewCell.swift
> +        positionLabel.text = String(index+1)
coding convention
```suggestion
        positionLabel.text = String(index + 1)
```

2023-10-11 11:57 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Stats/StatsViewModel.swift
> +        }
@hlinh88

> dùng tạm

Loại bỏ ngay mindset này nhé

> stat[0]

Tiếp tục lỗi cũ, lại access trực tiếp index element

2023-10-11 11:57 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Stats/StatsViewModel.swift
> +                self.navigator.toDetail(thisStat: stat)
@hlinh88 
dùng luôn drive cho gọn em nhé

2023-10-11 11:57 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Stats/StatsViewModel.swift
> +enum CategoryType: String {
tách file

2023-10-11 15:35 UTC, hlinh88 commented on FootballStats/FootballStats/Scenes/Stats/StatsViewModel.swift
> +        }
@dongtg-1485 đoạn này em có sử dụng `map` và subscribe trên scheduler `Serial` để lấy được đúng theo order ` [scorers, assists, redcards, yellowcards]` để display data đúng theo thứ tự ạ

2023-10-11 15:52 UTC, dongtg-1485 requested changes

2023-10-11 15:52 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Stats/Cell/StatsTableViewCell.swift
> +            guard let statistic = thisStat.statistics[safe: 0] else { return }
đã dùng [safe:] rồi thì việc check `isNotEmpty` không mang lại ý nghĩa gì nữa

2023-10-11 15:52 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Stats/Cell/StatsTableViewCell.swift
> +            guard let statistic = thisStat.statistics[safe: 0] else { return }
sửa cả các chỗ tương tự

2023-10-11 15:52 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Stats/StatsViewModel.swift
> +        }
làm lại đoạn này nhé

2023-10-11 15:52 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Stats/StatsViewModel.swift
> +        }
thử suy nghĩ xem vấn đề ở đoạn code này đang là gì và có cách nào làm clean hơn không nhé

2023-10-12 02:23 UTC, tuta-3205 commented on FootballStats/FootballStats/Scenes/Detail/DetailViewController.swift
> +            viewController.weightLabel.text = stat.player.weight
.then

2023-10-12 02:23 UTC, tuta-3205 commented on FootballStats/FootballStats/Scenes/Stats/Cell/StatsCollectionViewCell.swift
> +        bottomView.layer.maskedCorners = [.layerMinXMaxYCorner, .layerMaxXMaxYCorner]
then

2023-10-12 03:53 UTC, hlinh88 commented on FootballStats/FootballStats/Scenes/Stats/StatsViewModel.swift
> +        }
@dongtg-1485 em có sử dụng operator `zip` để combine các observable rồi xử lý thì không biết có hợp lý không anh nhỉ?

2023-10-12 04:29 UTC, dongtg-1485 approved these changes

2023-10-12 04:29 UTC, dongtg-1485 commented on FootballStats/FootballStats/Scenes/Stats/Cell/StatsCollectionViewCell.swift
> +        _ = topView.then {
sao đoạn này pải khai báo `_ = ` vậy em ?

2023-10-12 06:24 UTC, daolq-2712 approved these changes
OK!

2023-10-12 06:25 UTC, merged